# Generated by Django 4.2.4 on 2023-10-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_alter_profile_image_alter_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.EmailField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
