# Generated by Django 4.2.4 on 2023-09-26 12:11

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_productimages_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='prd', unique=True)),
                ('title', models.CharField(default='fresh pear', max_length=100)),
                ('image', models.ImageField(default='product.jpg', upload_to=core.models.user_directory_path)),
                ('description', models.TextField(blank=True, default='this is the product', null=True)),
                ('more_description', models.TextField(blank=True, default='this is more product', null=True)),
                ('information', models.TextField(blank=True, default='this is the information part', null=True)),
                ('price', models.DecimalField(decimal_places=3, default='100,000', max_digits=999999999999999999)),
                ('old_price', models.DecimalField(decimal_places=3, default='200,000', max_digits=999999999999999999)),
                ('specifications', models.TextField(blank=True, default='', null=True)),
                ('product_status', models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('regected', 'Rejected'), ('in_review', 'In_review'), ('published', 'Published')], default='in_review', max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('digital', models.BooleanField(default=False)),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=30, prefix='sku', unique=True)),
                ('date', models.TimeField(auto_now_add=True)),
                ('updated', models.TimeField(blank=True, null=True)),
                ('Vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vendor')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory', to='core.category')),
            ],
            options={
                'verbose_name_plural': ' sub products',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='information',
            field=models.TextField(blank=True, default='this is the information part', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='more_description',
            field=models.TextField(blank=True, default='this is more product', null=True),
        ),
        migrations.CreateModel(
            name='Sub_ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='product.jpg', upload_to='Sub_product_images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_images', to='core.sub_product')),
            ],
            options={
                'verbose_name_plural': 'Sub Product Images',
            },
        ),
        migrations.AddField(
            model_name='sub_product',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subproduct', to='core.product'),
        ),
        migrations.AddField(
            model_name='sub_product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
