# Generated by Django 4.2.4 on 2023-09-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sub_product_product_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_productimages',
            name='product',
        ),
        migrations.DeleteModel(
            name='Sub_Product',
        ),
        migrations.DeleteModel(
            name='Sub_ProductImages',
        ),
    ]
