# Generated by Django 4.2.4 on 2023-09-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sub_product_sub_productimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_productimages',
            old_name='product',
            new_name='subproduct',
        ),
    ]
