# Generated by Django 4.2.4 on 2023-09-26 12:44

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_product_sub_productimages_subproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_product',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sub_product'),
        ),
        migrations.AlterField(
            model_name='sub_product',
            name='spid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='sprd', unique=True),
        ),
    ]
