# Generated by Django 4.2.4 on 2023-09-26 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_sub_product_product_product_sub_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='subproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_images', to='core.sub_productimages')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_images', to='core.sub_product')),
            ],
            options={
                'verbose_name_plural': ' sub Products',
            },
        ),
    ]
