# Generated by Django 4.2.4 on 2023-09-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_subproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subproduct',
        ),
    ]
