# Generated by Django 4.2.4 on 2023-09-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_subproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_product',
        ),
        migrations.AddField(
            model_name='product',
            name='products',
            field=models.ManyToManyField(to='core.sub_product'),
        ),
    ]
