# Generated by Django 4.2.4 on 2023-10-01 05:01

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('core', '0013_alter_sub_productimages_subproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_productimages',
            name='subproduct',
        ),
        migrations.RemoveField(
            model_name='product',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Sub_Product',
        ),
        migrations.DeleteModel(
            name='Sub_ProductImages',
        ),
    ]
