# Generated by Django 4.2.4 on 2023-10-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
