# Generated by Django 4.2.4 on 2023-10-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_productreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=4, default='200,000', max_digits=999999999999999999),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=4, default='100,000', max_digits=999999999999999999),
        ),
    ]
