# Generated by Django 4.2.4 on 2023-10-22 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_colorcategory_languagecategory_sizecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colorcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colorcategory', to='core.colorcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='languagecategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languagecategory', to='core.languagecategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizecategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizecategory', to='core.sizecategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='tagcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagcategory', to='core.tagcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='typecategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typecategory', to='core.typecategory'),
        ),
    ]
