# Generated by Django 4.2.4 on 2023-10-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_product_colorcategory_product_languagecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='colorcategory',
            name='image',
            field=models.ImageField(blank=True, default='category.jpg', null=True, upload_to='colorcategory'),
        ),
        migrations.AlterField(
            model_name='languagecategory',
            name='image',
            field=models.ImageField(blank=True, default='category.jpg', null=True, upload_to='languagecategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sizecategory',
            name='image',
            field=models.ImageField(blank=True, default='category.jpg', null=True, upload_to='sizecategory'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='image',
            field=models.ImageField(blank=True, default='category.jpg', null=True, upload_to='tagcategory'),
        ),
        migrations.AlterField(
            model_name='typecategory',
            name='image',
            field=models.ImageField(blank=True, default='category.jpg', null=True, upload_to='typecategory'),
        ),
    ]
