# Generated by Django 4.2.4 on 2023-10-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_cartorder_price_alter_cartorderitems_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
