# Generated by Django 4.2.4 on 2023-10-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_cartorder_price_alter_cartorderitems_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='image',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
