# Generated by Django 4.2.4 on 2023-10-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adress',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adress',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adress',
            name='mobile',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adress',
            name='postcode',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adress',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='image',
            field=models.ImageField(blank=True, default='category.jpg', null=True, upload_to='cartorderitems'),
        ),
    ]
