# Generated by Django 4.2.4 on 2023-10-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_adress_city_adress_firstname_adress_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='postcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
