# Generated by Django 4.2.4 on 2023-10-24 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_adress_mobile_alter_adress_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adress'),
        ),
    ]
