# Generated by Django 4.2.4 on 2023-10-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_cartorder_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='state',
            new_name='stateadress',
        ),
    ]
