# Generated by Django 4.2.7 on 2023-11-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rename_state_adress_stateadress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagecategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sizecategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tagcategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='typecategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='Vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vendor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colorcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colorcategory', to='core.colorcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='languagecategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languagecategory', to='core.languagecategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizecategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizecategory', to='core.sizecategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tagcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagcategory', to='core.tagcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='typecategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typecategory', to='core.typecategory'),
        ),
    ]
