# Generated by Django 4.2.7 on 2023-11-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_languagecategory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='code',
            field=models.CharField(default='کد رهگیری سفارش بزودی قرار خواهد گرفت', max_length=200),
        ),
    ]
