# Generated by Django 4.2.7 on 2023-11-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_cartorder_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='mobile',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='postcode',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
