# Generated by Django 4.2.7 on 2023-11-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_adress_mobile_alter_adress_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='postcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
